// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataLayer.Entity
{
    public partial class OpCode
    {
        public int OpCodeID { get; set; }
        public string OperationName { get; set; }
    }
}