// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataLayer.Entity
{
    public partial class PartTypes
    {
        public int PartTypeID { get; set; }
        public string PartTypeName { get; set; }
        public int? PartCategoryID { get; set; }

        public virtual PartCategory PartCategory { get; set; }
    }
}