// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataLayer.Entity
{
    public partial class TransActionType
    {
        public int TransactionsTypeID { get; set; }
        public string TransactionTypeName { get; set; }
    }
}