// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class AssetConfiguration : IEntityTypeConfiguration<Asset>
    {
        public void Configure(EntityTypeBuilder<Asset> entity)
        {
            entity.Property(e => e.AddedBy).HasMaxLength(60);

            entity.Property(e => e.AssetDescription).HasMaxLength(512);

            entity.Property(e => e.AssetName).HasMaxLength(120);

            entity.Property(e => e.Location)
                .HasMaxLength(10)
                .IsFixedLength(true);

            entity.Property(e => e.ManuPartNum)
                .HasMaxLength(120)
                .IsFixedLength(true);

            entity.Property(e => e.ModifiedBy).HasMaxLength(60);

            entity.Property(e => e.Price).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.PurchaseDate).HasColumnType("date");

            entity.Property(e => e.SerialNumber).HasMaxLength(75);

            entity.Property(e => e.Tag).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Asset> entity);
    }
}
