// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class BOMListItemConfiguration : IEntityTypeConfiguration<BOMListItem>
    {
        public void Configure(EntityTypeBuilder<BOMListItem> entity)
        {
            entity.Property(e => e.Area).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.AssemblyArea).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.AssemblyDepth).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.AssemblyHieght).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.AssemblyName).HasMaxLength(255);

            entity.Property(e => e.AssemblyWidth).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.FunctionalName).HasMaxLength(255);

            entity.Property(e => e.JobName).HasMaxLength(255);

            entity.Property(e => e.LaborAmount).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.Length).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.Markup).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.Note).HasMaxLength(255);

            entity.Property(e => e.PartClass).HasMaxLength(255);

            entity.Property(e => e.PartIdentifier).HasMaxLength(255);

            entity.Property(e => e.PartLabel).HasMaxLength(255);

            entity.Property(e => e.PartType).HasMaxLength(255);

            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.Rate).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.SourceDescription).HasMaxLength(255);

            entity.Property(e => e.SourceName).HasMaxLength(255);

            entity.Property(e => e.SubAssemblyArea).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.SubAssemblyDepth).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.SubAssemblyHieght).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.SubAssemblyID).HasMaxLength(255);

            entity.Property(e => e.SubAssemblyWidth).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.Tax).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.Thick).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.Waste).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.Weight).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.Width).HasColumnType("decimal(18, 4)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BOMListItem> entity);
    }
}
