// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class ClaimDocumentConfiguration : IEntityTypeConfiguration<ClaimDocument>
    {
        public void Configure(EntityTypeBuilder<ClaimDocument> entity)
        {
            entity.Property(e => e.DocumentDesciption)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.DocumentExtension)
                .HasMaxLength(6)
                .IsUnicode(false);

            entity.HasOne(d => d.ClaimItem)
                .WithMany(p => p.ClaimDocument)
                .HasForeignKey(d => d.ClaimItemID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ClaimDocument_ClaimItem");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClaimDocument> entity);
    }
}
