// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class JobConfiguration : IEntityTypeConfiguration<Job>
    {
        public void Configure(EntityTypeBuilder<Job> entity)
        {
            entity.Property(e => e.ParentID).HasDefaultValueSql("((0))");

            entity.Property(e => e.company_id).HasDefaultValueSql("((0))");

            entity.Property(e => e.jobdesc)
                .HasMaxLength(500)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.jobname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.jobnumber).HasDefaultValueSql("((0))");

            entity.Property(e => e.leftNode).HasDefaultValueSql("((0))");

            entity.Property(e => e.project_id).HasDefaultValueSql("((0))");

            entity.Property(e => e.rightnode).HasDefaultValueSql("((0))");

            entity.Property(e => e.start_ts).HasColumnType("datetime");

            entity.Property(e => e.structurelevel).HasDefaultValueSql("((0))");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Job> entity);
    }
}
