// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class JobSiteConfiguration : IEntityTypeConfiguration<JobSite>
    {
        public void Configure(EntityTypeBuilder<JobSite> entity)
        {
            entity.Property(e => e.City).HasMaxLength(50);

            entity.Property(e => e.State).HasMaxLength(50);

            entity.Property(e => e.StreetAddress).HasMaxLength(50);

            entity.Property(e => e.Zip).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<JobSite> entity);
    }
}
