// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class ManuConfiguration : IEntityTypeConfiguration<Manu>
    {
        public void Configure(EntityTypeBuilder<Manu> entity)
        {
            entity.Property(e => e.ManuCategoryID).HasDefaultValueSql("((0))");

            entity.Property(e => e.Manufacturer)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Phone)
                .HasMaxLength(16)
                .HasDefaultValueSql("(' ')")
                .IsFixedLength(true);

            entity.Property(e => e.WebAddress)
                .HasMaxLength(120)
                .HasDefaultValueSql("(' ')")
                .IsFixedLength(true);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Manu> entity);
    }
}
