// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class NFRCConfiguration : IEntityTypeConfiguration<NFRC>
    {
        public void Configure(EntityTypeBuilder<NFRC> entity)
        {
            entity.HasKey(e => e.CPD_ID);

            entity.Property(e => e.CPD).HasMaxLength(255);

            entity.Property(e => e.FrameMaterial)
                .HasMaxLength(65)
                .IsFixedLength(true);

            entity.Property(e => e.FrameSashType).HasMaxLength(255);

            entity.Property(e => e.GapFill).HasMaxLength(255);

            entity.Property(e => e.GlassName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Grid).HasMaxLength(255);

            entity.Property(e => e.IGU)
                .HasMaxLength(75)
                .IsFixedLength(true);

            entity.Property(e => e.LowE).HasMaxLength(255);

            entity.Property(e => e.ManufacturerProductCode).HasMaxLength(255);

            entity.Property(e => e.ProductDescription)
                .HasMaxLength(240)
                .IsUnicode(false);

            entity.Property(e => e.Spacer).HasMaxLength(255);

            entity.Property(e => e.SystemName)
                .HasMaxLength(120)
                .IsUnicode(false);

            entity.Property(e => e.Tint).HasMaxLength(255);

            entity.Property(e => e.UnitType)
                .HasMaxLength(70)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<NFRC> entity);
    }
}
