// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class OrderRecieptConfiguration : IEntityTypeConfiguration<OrderReciept>
    {
        public void Configure(EntityTypeBuilder<OrderReciept> entity)
        {
            entity.HasKey(e => e.OrderReceiptID)
                .HasName("PK_Reciept");

            entity.Property(e => e.ReceiptDate).HasColumnType("date");

            entity.HasOne(d => d.Employee)
                .WithMany(p => p.OrderReciept)
                .HasForeignKey(d => d.EmployeeID)
                .HasConstraintName("FK_OrderReciept_Employee");

            entity.HasOne(d => d.PurchaseOrder)
                .WithMany(p => p.OrderReciept)
                .HasForeignKey(d => d.PurchaseOrderID)
                .HasConstraintName("FK_OrderReciept_PurchaseOrder");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderReciept> entity);
    }
}
