// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class OrderFeeConfiguration : IEntityTypeConfiguration<OrderFee>
    {
        public void Configure(EntityTypeBuilder<OrderFee> entity)
        {
            entity.Property(e => e.Cost).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.Extension).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.FeeName).HasMaxLength(200);

            entity.Property(e => e.Qnty).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.PurchaseOrder)
                .WithMany(p => p.OrderFee)
                .HasForeignKey(d => d.PurchaseOrderID)
                .HasConstraintName("FK_OrderFee_PurchaseOrder");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderFee> entity);
    }
}
