// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class OrderReceiptItemsConfiguration : IEntityTypeConfiguration<OrderReceiptItems>
    {
        public void Configure(EntityTypeBuilder<OrderReceiptItems> entity)
        {
            entity.HasKey(e => e.OrderReceiptLineID);

            entity.Property(e => e.Balance).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.Description).HasMaxLength(1250);

            entity.Property(e => e.Extended).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.InventoryAmount).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.Note).HasMaxLength(240);

            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.QuantityOrdered).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.QuantityReceived).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.OrderReceipt)
                .WithMany(p => p.OrderReceiptItems)
                .HasForeignKey(d => d.OrderReceiptID)
                .HasConstraintName("FK_OrderReceiptItems_OrderReciept");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderReceiptItems> entity);
    }
}
