// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class PartTypesConfiguration : IEntityTypeConfiguration<PartTypes>
    {
        public void Configure(EntityTypeBuilder<PartTypes> entity)
        {
            entity.HasKey(e => e.PartTypeID);

            entity.Property(e => e.PartTypeName)
                .HasMaxLength(75)
                .IsFixedLength(true);

            entity.HasOne(d => d.PartCategory)
                .WithMany(p => p.PartTypes)
                .HasForeignKey(d => d.PartCategoryID)
                .HasConstraintName("FK_PartTypes_PartCategory");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PartTypes> entity);
    }
}
