// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.Property(e => e.ArchDescription).HasMaxLength(200);

            entity.Property(e => e.D).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.DeliveredDate).HasColumnType("date");

            entity.Property(e => e.H).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.ProductionDate).HasColumnType("date");

            entity.Property(e => e.RoomName).HasMaxLength(50);

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.Property(e => e.W).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.Job)
                .WithMany(p => p.Product)
                .HasForeignKey(d => d.JobID)
                .HasConstraintName("FK_Product_Job");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Product> entity);
    }
}
