// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class PurchaseLineItemConfiguration : IEntityTypeConfiguration<PurchaseLineItem>
    {
        public void Configure(EntityTypeBuilder<PurchaseLineItem> entity)
        {
            entity.HasKey(e => e.LineID);

            entity.Property(e => e.AmountReceived)
                .HasColumnType("decimal(18, 4)")
                .HasDefaultValueSql("((0.0))");

            entity.Property(e => e.BCode).HasMaxLength(50);

            entity.Property(e => e.Description)
                .HasMaxLength(1024)
                .IsUnicode(false)
                .HasDefaultValueSql("(' ')");

            entity.Property(e => e.Extended)
                .HasColumnType("decimal(18, 4)")
                .HasDefaultValueSql("((0.0))");

            entity.Property(e => e.Length)
                .HasColumnType("decimal(18, 4)")
                .HasDefaultValueSql("((0.00))");

            entity.Property(e => e.Qnty)
                .HasColumnType("decimal(18, 4)")
                .HasDefaultValueSql("((1.0))");

            entity.Property(e => e.Recieved).HasDefaultValueSql("((0))");

            entity.Property(e => e.Thick)
                .HasColumnType("decimal(18, 4)")
                .HasDefaultValueSql("((0.00))");

            entity.Property(e => e.UnitCost)
                .HasColumnType("decimal(18, 4)")
                .HasDefaultValueSql("((0.0))");

            entity.Property(e => e.Weight)
                .HasColumnType("decimal(18, 4)")
                .HasDefaultValueSql("((0.00))");

            entity.Property(e => e.Width)
                .HasColumnType("decimal(18, 4)")
                .HasDefaultValueSql("((0.00))");

            entity.HasOne(d => d.PurchaseOrder)
                .WithMany(p => p.PurchaseLineItem)
                .HasForeignKey(d => d.PurchaseOrderID)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_PurchaseLineItem_PurchaseOrder");

            entity.HasOne(d => d.UnitOfMeasure)
                .WithMany(p => p.PurchaseLineItem)
                .HasForeignKey(d => d.UnitOfMeasureID)
                .HasConstraintName("FK_PurchaseLineItem_UnitOfMeasure");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseLineItem> entity);
    }
}
