// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class ResourceVersionConfiguration : IEntityTypeConfiguration<ResourceVersion>
    {
        public void Configure(EntityTypeBuilder<ResourceVersion> entity)
        {
            entity.Property(e => e.ModDate).HasColumnType("date");

            entity.Property(e => e.ModifiedBy).HasMaxLength(50);

            entity.Property(e => e.Src).HasMaxLength(90);

            entity.Property(e => e.VersionComment).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ResourceVersion> entity);
    }
}
