// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class ShipByConfiguration : IEntityTypeConfiguration<ShipBy>
    {
        public void Configure(EntityTypeBuilder<ShipBy> entity)
        {
            entity.HasKey(e => e.ShipID);

            entity.Property(e => e.ShipByName)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ShipBy> entity);
    }
}
