// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class SubAssemblyConfiguration : IEntityTypeConfiguration<SubAssembly>
    {
        public void Configure(EntityTypeBuilder<SubAssembly> entity)
        {
            entity.Property(e => e.D).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.H).HasColumnType("decimal(18, 4)");

            entity.Property(e => e.MakeFile).HasMaxLength(240);

            entity.Property(e => e.SubAssemblyName).HasMaxLength(50);

            entity.Property(e => e.W).HasColumnType("decimal(18, 4)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SubAssembly> entity);
    }
}
