// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class TaskConfiguration : IEntityTypeConfiguration<Task>
    {
        public void Configure(EntityTypeBuilder<Task> entity)
        {
            entity.HasKey(e => e.TaskCode);

            entity.Property(e => e.TaskCode).ValueGeneratedNever();

            entity.Property(e => e.ActualTime).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.CostCalculation)
                .HasMaxLength(60)
                .IsFixedLength(true);

            entity.Property(e => e.EstimatedTime).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.MarkUp).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.Rate).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.TaskDescription)
                .HasMaxLength(240)
                .IsUnicode(false);

            entity.Property(e => e.TaskName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Total).HasColumnType("decimal(18, 4)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Task> entity);
    }
}
