// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class WorkOrderRoutingConfiguration : IEntityTypeConfiguration<WorkOrderRouting>
    {
        public void Configure(EntityTypeBuilder<WorkOrderRouting> entity)
        {
            entity.HasKey(e => e.WorkOrderID);

            entity.Property(e => e.ActualCost).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.ActualEndDate).HasColumnType("datetime");

            entity.Property(e => e.ActualStartDate).HasColumnType("datetime");

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.Property(e => e.PlannedCost).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.ScheduledEndDate).HasColumnType("datetime");

            entity.Property(e => e.ScheduledStartDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkOrderRouting> entity);
    }
}
