// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataLayer.Data;
using DataLayer.Entity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace DataLayer.Data.Configurations
{
    public partial class WorkCenterConfiguration : IEntityTypeConfiguration<WorkCenter>
    {
        public void Configure(EntityTypeBuilder<WorkCenter> entity)
        {
            entity.Property(e => e.Availabilty).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.CostRate).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.WorkCenterName)
                .HasMaxLength(75)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WorkCenter> entity);
    }
}
